# Generated by Django 4.2.3 on 2023-07-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='consolas',
            field=models.CharField(choices=[('PLAYSTATION_4', 'PlayStation 4'), ('PLAYSTATION_5', 'PlayStation 5'), ('NINTENDO_SWITCH', 'Nintendo Switch'), ('XBOX_ONE', 'Xbox One'), ('PC', 'PC'), ('OTROS', 'Otros')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
