# Generated by Django 4.2.3 on 2023-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('productora', models.CharField(max_length=50)),
                ('actor_protagonista', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('DRAMA', 'Drama'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comedia'), ('TERROR', 'Terror'), ('OTROS', 'Otros')], max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('productora', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('FPS', 'FPS'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ESTRATEGIA', 'Estrategia'), ('TERROR', 'Terror'), ('OTROS', 'Otros')], max_length=20)),
                ('fecha_estreno', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
